name: Create Release with Graphs

on:
  push:
    tags:
      - "v*"  # Triggers only when you push a tag like v1.0, v2.0, etc.

permissions:
  contents: write

jobs:
  release-charts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r .github/requirements.txt

    - name: Generate Images
      run: |
        python .github/scripts/generate_images.py

    # This step creates the release and uploads the images
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: output_charts/*.png
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
